spring.application.name=servicemanagement

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6oknnfgi27c73egabpg-a.singapore-postgres.render.com:5432/servicemanagement_gk82
spring.datasource.username=servicemanagement_user
spring.datasource.password=geoZ4BZJ6o3UYam7HL6anDJ65eElzSK0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true