spring.application.name=servicemanagement


spring.datasource.url=jdbc:postgresql://db.pedovjeteawqcuthvdxz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=nithya_rooba

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
